# Generated by Django 4.2 on 2023-08-08 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cencel_order', 'Can cencel order')]},
        ),
    ]
